<?php

class User
{
    public $user_name;
    public $password;
    public $logged_in;

    public function login(){
       echo $this->user_name." logged in ".PHP_EOL;
       echo " go to home page ".PHP_EOL;
       $this->logged_in = true;
    }

    public function logout(){
       echo $this ->user_name."logged out".PHP_EOL;
       $this ->logged_in = false;
    }
}
//$normal = new User();
//$normal ->user_name = "nhung";
//$normal ->login();

class Admin extends User{
    public function login()
    {
        parent::login(); // TODO: Change the autogenerated stub
        echo $this->user_name." logged and go to panel ". PHP_EOL;
    }

    public function createPost($post_name){
        if($this->logged_in){
            echo "Admin create post with title ".$post_name.PHP_EOL  ;
        }else
            echo "do not have permission".PHP_EOL;
    }
}
$admin = new Admin();
$admin->user_name = "nhung";
$admin->login();
//var_dump($admin->createPost('nga'));